// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RepositorierMock is an autogenerated mock type for the Repositorier type
type RepositorierMock struct {
	mock.Mock
}

// Get provides a mock function with given fields: shortUrlId
func (_m *RepositorierMock) Get(shortUrlId string) (string, error) {
	ret := _m.Called(shortUrlId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortUrlId)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortUrlId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: url
func (_m *RepositorierMock) Save(url string) (int, error) {
	ret := _m.Called(url)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
